name: yotes
version: 1.0.2+1
publish_to: none
description: A Note taking app build by Shakib.
author: devShakib
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  firebase_core: 1.2.1
  firebase_auth: 1.3.0
  cloud_firestore: 2.2.1
  flutter_facebook_auth: ^3.5.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

